"use strict";
exports.__esModule = true;
var book_1 = require("./abstraction/refined/book");
var paper_1 = require("./abstraction/refined/paper");
var white_paper_1 = require("./abstraction/refined/white-paper");
var formatter_factory_1 = require("./factory/formatter-factory");
var formatter_type_1 = require("./factory/formatter-type");
var brochure_1 = require("./abstraction/refined/brochure");
var thesis_1 = require("./abstraction/refined/thesis");
var draft_1 = require("./abstraction/refined/draft");
function clientCode() {
    var draftFormatter = formatter_factory_1.FormatterFactory.getType(formatter_type_1.FormatterType.STANDARD);
    var draft = new draft_1.Draft(draftFormatter);
    draft.changeText("Text of the draft");
    draft.print();
    var formatter = formatter_factory_1.FormatterFactory.getType(formatter_type_1.FormatterType.VANCOUVER);
    var brochure = new brochure_1.Brochure(formatter);
    brochure.changeText("Text of the brochure");
    brochure.print();
    console.log("*************************************************************");
    var thesis = new thesis_1.Thesis(formatter);
    thesis.changeAuthor("Juan Pérez");
    thesis.changeTitle("Design Patterns");
    thesis.changeText("Text of the thesis");
    thesis.changeReferences("References of the thesis");
    thesis.print();
    console.log("*************************************************************");
    var book = new book_1.Book(formatter);
    book.changeAuthor("Robert C. Martin");
    book.changeTitle("Clean Code");
    book.changeText("Text of the book");
    book.print();
    console.log("*************************************************************");
    var whitePaper = new white_paper_1.WhitePaper(formatter);
    whitePaper.changeAuthor("Juan Pérez");
    whitePaper.changeTitle("Design Patterns");
    whitePaper.changeText("Text of the paper");
    whitePaper.changeReferences("References of the white paper");
    whitePaper.print();
    console.log("*************************************************************");
    var apaFormatter = formatter_factory_1.FormatterFactory.getType(formatter_type_1.FormatterType.APA);
    var paper = new paper_1.Paper(apaFormatter);
    paper.changeAuthor("Juan Pérez");
    paper.changeTitle("Design Patterns");
    paper.changeText("Text of the paper");
    paper.changeReferences("References of the paper");
    paper.print();
}
clientCode();
